package pg

// Env-gated tests for the admin credential store on the real schema (migration
// 0008): transactional mutation/audit atomicity, immediate rotation and
// revocation effects, expiry, tenant-predicated listings, the last-use
// throttle, authentication-audit rows, and the schema-level scope CHECK as the
// last line of defense. Run with TEST_DATABASE_URL; skipped otherwise and
// serialized on the shared advisory lock.

import (
	"context"
	"database/sql"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/knowledge-base/knowledge-base-gateway/internal/adminauth"
	"github.com/knowledge-base/knowledge-base-gateway/internal/mgmt"
)

func newAdminTestStore(t *testing.T) (*AdminCredentialStore, *DB, *sql.DB) {
	t.Helper()
	dsn := testDatabaseURL(t)
	ensureAsyncSchema(t, dsn)
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })
	cleanAdminCredentials(t, db)
	ctx := context.Background()
	pool, err := Connect(ctx, dsn)
	if err != nil {
		t.Fatalf("pool connect: %v", err)
	}
	t.Cleanup(pool.Close)
	return &AdminCredentialStore{DB: pool}, pool, db
}

func cleanAdminCredentials(t *testing.T, db *sql.DB) {
	t.Helper()
	for _, stmt := range []string{
		// This package's tests run in file order (admin_test.go first), so the
		// tenants the credentials reference cannot rely on ledger_test's
		// seeding: upsert them here, idempotently.
		`INSERT INTO tenants (id, name) VALUES ('tenant_default', 'Default Tenant') ON CONFLICT (id) DO NOTHING`,
		`INSERT INTO tenants (id, name) VALUES ('tenant_eu', 'EU Tenant') ON CONFLICT (id) DO NOTHING`,
		// Rotation lineage self-references, so credentials go in one stroke;
		// audit rows generated by these tests carry the marker actions.
		`DELETE FROM admin_credentials`,
		`DELETE FROM admin_audit WHERE action LIKE 'admin_credential%' OR action LIKE 'admin_auth%'`,
	} {
		if _, err := db.Exec(stmt); err != nil {
			t.Fatalf("clean admin tables: %v: %v", stmt, err)
		}
	}
}

func adminTestRecord(t *testing.T, id, subject string, scopes []string, tenant string, expires time.Time) (adminauth.CredentialRecord, string) {
	t.Helper()
	plain, err := adminauth.GenerateCredential()
	if err != nil {
		t.Fatal(err)
	}
	salt, err := adminauth.NewSalt()
	if err != nil {
		t.Fatal(err)
	}
	return adminauth.CredentialRecord{
		ID: id, AdminSubject: subject,
		Salt: salt, Hash: adminauth.HashCredential(salt, plain),
		Prefix: adminauth.DisplayPrefix(plain), Scopes: mustParseScopes(t, scopes),
		Status: adminauth.StatusActive, TenantID: tenant,
		ExpiresAt: expires, CreatedAt: time.Now(),
	}, plain
}

func mustParseScopes(t *testing.T, raw []string) []adminauth.Scope {
	t.Helper()
	scopes, err := adminauth.ParseScopes(raw)
	if err != nil {
		t.Fatalf("parse scopes: %v", err)
	}
	return scopes
}

func countAdminAudit(t *testing.T, db *sql.DB, action string) int {
	t.Helper()
	var n int
	if err := db.QueryRow(`SELECT count(*) FROM admin_audit WHERE action = $1`, action).Scan(&n); err != nil {
		t.Fatalf("count audit: %v", err)
	}
	return n
}

func TestAdminCredentialStoreLifecycle(t *testing.T) {
	s, _, db := newAdminTestStore(t)
	ctx := context.Background()
	now := time.Now()

	rec, plain := adminTestRecord(t, "adm_life_1", "ops", []string{"operator"}, "tenant_eu", now.Add(time.Hour))
	op := mgmt.AdminOp{CreatedAt: now, Action: "admin_credential_create", Target: "ops",
		AdminSubject: "bootstrap-token", Detail: []byte(`{}`),
		Actor: mgmt.AdminActor{TenantID: "", Scopes: []string{"platform-admin"}, Bootstrap: true}}
	if err := s.Create(ctx, rec, op); err != nil {
		t.Fatalf("create: %v", err)
	}
	if countAdminAudit(t, db, "admin_credential_create") != 1 {
		t.Fatal("create must commit exactly one audit row")
	}

	// Resolve: right plaintext succeeds, near-miss fails.
	got, err := s.Resolve(ctx, plain, now)
	if err != nil || got.ID != rec.ID || got.AdminSubject != "ops" {
		t.Fatalf("resolve: %v %+v", err, got)
	}
	if _, err := s.Resolve(ctx, plain+"x", now); !errors.Is(err, adminauth.ErrInvalid) {
		t.Fatalf("near-miss must be invalid, got %v", err)
	}

	// Actor attribution landed in the audit detail.
	var detail []byte
	if err := db.QueryRow(`SELECT detail FROM admin_audit WHERE action = 'admin_credential_create' LIMIT 1`).Scan(&detail); err != nil {
		t.Fatalf("read audit detail: %v", err)
	}
	if !containsAll(string(detail), `"bootstrap"`, `"subject"`) {
		t.Fatalf("audit detail must carry the actor block: %s", detail)
	}

	// Rotate: one transaction — successor active, predecessor revoked, one
	// audit row. The old plaintext fails immediately, the new one resolves.
	succ, succPlain := adminTestRecord(t, "adm_life_2", "ops", []string{"operator"}, "tenant_eu", now.Add(time.Hour))
	succ.RotatedFrom = rec.ID
	rotOp := mgmt.AdminOp{CreatedAt: now, Action: "admin_credential_rotate", Target: rec.ID, Detail: []byte(`{}`)}
	if err := s.Rotate(ctx, rec.ID, succ, now, rotOp); err != nil {
		t.Fatalf("rotate: %v", err)
	}
	if _, err := s.Resolve(ctx, plain, now); err == nil {
		t.Fatal("predecessor must fail immediately after rotation")
	}
	if _, err := s.Resolve(ctx, succPlain, now); err != nil {
		t.Fatalf("successor must resolve: %v", err)
	}
	if countAdminAudit(t, db, "admin_credential_rotate") != 1 {
		t.Fatal("rotate must commit exactly one audit row")
	}

	// Rotating a revoked predecessor rolls back: the successor of a failed
	// rotation never appears.
	succ2, _ := adminTestRecord(t, "adm_life_3", "ops", []string{"viewer"}, "", time.Time{})
	if err := s.Rotate(ctx, rec.ID, succ2, now, mgmt.AdminOp{Action: "admin_credential_rotate"}); !errors.Is(err, adminauth.ErrInactive) {
		t.Fatalf("rotating a revoked credential must be ErrInactive, got %v", err)
	}
	var n int
	if err := db.QueryRow(`SELECT count(*) FROM admin_credentials WHERE id = 'adm_life_3'`).Scan(&n); err != nil || n != 0 {
		t.Fatalf("failed rotation must write nothing: n=%d err=%v", n, err)
	}

	// Revoke: idempotent, one audit row for the real mutation only.
	if err := s.Revoke(ctx, succ.ID, now, mgmt.AdminOp{CreatedAt: now, Action: "admin_credential_revoke", Target: succ.ID}); err != nil {
		t.Fatalf("revoke: %v", err)
	}
	if err := s.Revoke(ctx, succ.ID, now, mgmt.AdminOp{CreatedAt: now, Action: "admin_credential_revoke", Target: succ.ID}); err != nil {
		t.Fatalf("re-revoke must be a no-op success, got %v", err)
	}
	if countAdminAudit(t, db, "admin_credential_revoke") != 1 {
		t.Fatal("revoke must commit exactly one audit row (the no-op none)")
	}
	if _, err := s.Resolve(ctx, succPlain, now); err == nil {
		t.Fatal("revoked credential must fail immediately")
	}
	if _, err := s.Get(ctx, "adm_missing"); !errors.Is(err, adminauth.ErrNotFound) {
		t.Fatalf("unknown credential must be ErrNotFound, got %v", err)
	}
}

// TestAdminCredentialExpiry pins the database-backed expiry decision.
func TestAdminCredentialExpiry(t *testing.T) {
	s, _, _ := newAdminTestStore(t)
	ctx := context.Background()
	now := time.Now()
	rec, plain := adminTestRecord(t, "adm_exp_1", "temp", []string{"viewer"}, "", now.Add(-time.Second))
	if err := s.Create(ctx, rec, mgmt.AdminOp{Action: "admin_credential_create"}); err != nil {
		t.Fatalf("create: %v", err)
	}
	if _, err := s.Resolve(ctx, plain, now); !errors.Is(err, adminauth.ErrExpired) {
		t.Fatalf("expired credential must answer ErrExpired, got %v", err)
	}
}

// TestAdminCredentialTenantList pins the mandatory tenant predicate on
// listings and the audit rows for authentication events plus the throttled
// last-use stamp.
func TestAdminCredentialTenantListAndBookkeeping(t *testing.T) {
	s, _, db := newAdminTestStore(t)
	ctx := context.Background()
	now := time.Now()

	recEU, plainEU := adminTestRecord(t, "adm_t_1", "euops", []string{"viewer"}, "tenant_eu", time.Time{})
	if err := s.Create(ctx, recEU, mgmt.AdminOp{Action: "admin_credential_create"}); err != nil {
		t.Fatalf("create eu: %v", err)
	}
	recHome, _ := adminTestRecord(t, "adm_t_2", "homeops", []string{"viewer"}, "tenant_default", time.Time{})
	if err := s.Create(ctx, recHome, mgmt.AdminOp{Action: "admin_credential_create"}); err != nil {
		t.Fatalf("create home: %v", err)
	}

	all, err := s.List(ctx, "", "")
	if err != nil || len(all) != 2 {
		t.Fatalf("global list: %v %d", err, len(all))
	}
	eu, err := s.List(ctx, "", "tenant_eu")
	if err != nil || len(eu) != 1 || eu[0].ID != recEU.ID {
		t.Fatalf("tenant-predicated list must return only the tenant rows: %v %+v", err, eu)
	}

	// Authentication bookkeeping: success rows carry the credential, failure
	// rows carry the reason class; last-used stamps are throttled.
	p := recEU.Principal()
	s.LogAuth(ctx, p, true, "", now)
	s.LogAuth(ctx, p, false, "revoked", now)
	if countAdminAudit(t, db, "admin_auth") != 1 || countAdminAudit(t, db, "admin_auth_failed") != 1 {
		t.Fatal("authentication events must be audited")
	}
	s.TouchLastUsed(ctx, recEU.ID, now)
	var lastUsed sql.NullTime
	if err := db.QueryRow(`SELECT last_used_at FROM admin_credentials WHERE id = $1`, recEU.ID).Scan(&lastUsed); err != nil {
		t.Fatalf("read last_used: %v", err)
	}
	if !lastUsed.Valid {
		t.Fatal("last_used_at must be stamped")
	}
	// Inside the throttle window the stamp does not move.
	s.TouchLastUsed(ctx, recEU.ID, now.Add(10*time.Second))
	var same sql.NullTime
	if err := db.QueryRow(`SELECT last_used_at FROM admin_credentials WHERE id = $1`, recEU.ID).Scan(&same); err != nil {
		t.Fatalf("re-read last_used: %v", err)
	}
	if !same.Valid || !same.Time.Equal(lastUsed.Time) {
		t.Fatal("last-used stamp must be throttled within the window")
	}
	_ = plainEU
}

// TestAdminCredentialSchemaChecks pins the migration's database boundary:
// scope values outside the closed vocabulary and empty grant sets are
// rejected by the CHECK constraints, never by application logic.
func TestAdminCredentialSchemaChecks(t *testing.T) {
	_, _, db := newAdminTestStore(t)
	cases := []struct {
		name    string
		scopes  string
		wantErr bool
	}{
		{"closed-vocabulary ok", `ARRAY['viewer','operator']`, false},
		{"invented scope rejected", `ARRAY['superuser']`, true},
		{"empty grant set rejected", `ARRAY[]::text[]`, true},
	}
	for _, tc := range cases {
		_, err := db.Exec(`
			INSERT INTO admin_credentials (id, admin_subject, credential_hash, credential_prefix, scopes, status, created_at)
			VALUES ('adm_check_'||$1, 's', decode(md5($1), 'hex'), 'kba_xx', `+tc.scopes+`, 'active', now())`, tc.name)
		if tc.wantErr && err == nil {
			t.Errorf("%s: schema must reject the row", tc.name)
		}
		if !tc.wantErr && err != nil {
			t.Errorf("%s: valid row rejected: %v", tc.name, err)
		}
	}
}

// TestAdminCredentialUnknownTenant pins the FK translation: creating a
// credential for an unknown tenant answers the domain error (a clean 400
// upstream), not a raw driver failure.
func TestAdminCredentialUnknownTenant(t *testing.T) {
	s, _, _ := newAdminTestStore(t)
	rec, _ := adminTestRecord(t, "adm_fk_1", "ops", []string{"viewer"}, "tenant_missing", time.Time{})
	err := s.Create(context.Background(), rec, mgmt.AdminOp{Action: "admin_credential_create"})
	if !errors.Is(err, adminauth.ErrUnknownTenant) {
		t.Fatalf("unknown tenant must translate to ErrUnknownTenant, got %v", err)
	}
}

func containsAll(haystack string, needles ...string) bool {
	for _, n := range needles {
		if !strings.Contains(haystack, n) {
			return false
		}
	}
	return true
}
